"""empty message

Revision ID: 9fedf28a4f57
Revises: 
Create Date: 2023-09-18 19:31:38.808903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fedf28a4f57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coinsurance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_of_transaction', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('request_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coinsurance', schema=None) as batch_op:
        batch_op.drop_column('request_id')
        batch_op.drop_column('type_of_transaction')

    # ### end Alembic commands ###
